### ISSUE TITLE
[REVIEW] Project Description & Documentation

### ISSUE THREAD

**Issue by ozszt1** [BevapnadeBerit/Sudoku_Visualizer#26]

**Comment by ozszt1** [comment]
A good beginning to the project description with clear information on what it is about and the resources that are used. It'll be interesting to see how the "How to run" section will be developed as that is probably the most valuable for those wanting to use the project. It would've also been interesting to know in which way the project tools, ChatGPT and Paint.NET, were used for the project but isn't necessarily a must.

The code documentation is done well. It's definitely good that viewers are notified of what is generated by ChatGPT and what is made by your own. The comments and brief descriptions are short and easy to understand all while being informative. Great job!

**Comment by sappoPrivy** [comment]
You have a main goal and sub goals in your project description which is good.
You could add a little more documentation in the code as it is a little difficult to follow along sometimes.
You could have included instructions, a little overview or documentation of the files. For example demo.py is the main file, it runs the game.... I find it much more easier if I know which file I should start looking in. Or you could include a little documentation in the top of your file...
