### ISSUE TITLE
[REVIEW] Use of Issues to resolve bugs

### ISSUE THREAD

**Issue by sappoPrivy** [BevapnadeBerit/Sudoku_Visualizer#29]

**Comment by sappoPrivy** [comment]
You have used issues to resolve bugs in a good way. The description is short and concise.

**Comment by ozszt1** [comment]
Very informative and detailed issues which even sometimes refers to previous issues or pull requests, something neither my own group had even thought of. Again, great use of labels in which you even tag which are low priority.
