### ISSUE TITLE
[REVIEW] Use of Branching and Pull Requests

### ISSUE THREAD

**Issue by sappoPrivy** [BevapnadeBerit/Sudoku_Visualizer#30]

**Comment by sappoPrivy** [comment]
The description of the pull requests where very thorough and detailed

**Comment by ozszt1** [comment]
The comments in the pull requests are extremely precise and explanatory which makes for a really nice overview of the PR. This definitely promotes great communication and is valuable to both parties. This way, you can easily look back and read what exactly was merged and perhaps more easily find the issue if merge conflicts were to occur. Even having a TL:DR is super helpful and definitely something that more people (aka... our group) should use.
